inject /usr/local/bin in path
MordFustang21/ide-gopls pull request #15
Opened 2021-03-05 18:48 UTC by MordFustang21

2021-03-06 03:22 UTC, Jorropo commented
This still doesn't work for me on Linux, how ever I found how to fix it.

Start atom including :
```
source ~/.bashrc
```

I've edited my `.desktop` for atom and it work like a charm now. :)

2021-03-18 20:22 UTC, jrkt requested changes

2021-03-18 20:22 UTC, jrkt commented on lib/main.js
> +const os = require('os');
Boo

2021-03-18 20:23 UTC, carsonoid commented on lib/main.js
> +const os = require('os');
Hoo

2025-05-14 20:06 UTC, closed without merging